observations_names:
  - "x"
  - "y"
  - "angle"
  - "v_x"
  - "v_y"
  - "angle_vel"

actions_names:
  - "F_side"
  - "F_vert"


nominal_policy:
  _target_: goalagent.env.lunar_lander.LunarLanderStabilizingPolicy


checkpoint_path: lunar_lander