_target_: src.policy.InvPendulumEnergyBasedFrictionAdaptive

gain: 0.03
action_min: -0.3
action_max: 0.3
friction_coef_est_init: 0
sampling_time: $ common.sampling_time
gain_adaptive: 0.003
pd_coefs: = [0.6, 0.2]
switch_loc: = np.cos(np.pi / 10)