_target_: src.system.InvertedPendulumWithFriction

## Redefine the parameters of the pendulum
# system_parameters_init: 
#   mass: 0.127
#   grav_const: 9.81
#   length: 0.337
#   friction_coeff: 0.01