_target_: src.system.InvertedPendulumWithMotor

## Redefine the parameters of the pendulum
# system_parameters_init: 
#   mass: 0.127
#   grav_const: 9.81
#   length: 0.337
#   motor_time_const: 0.05
#   motor_mass: 0.05
#   motor_radius: 0.04
